### ISSUE TITLE
Need to call setup after latest update

### ISSUE THREAD

**Issue by TheRealCatherine** [GracesGames/SimpleFileBrowser#27]
I'm not sure if I just messed something up when doing the latest update, but now I must call fileBrowserScript.SetupFileBrowser(ViewMode.Portrait or ViewMode.Landscape) or I will get errors from _uiscript not being set in FileBrowser.cs

this is totally fine, but if it is in fact required now the documentation should be updated :-)

Thanks so much for continuing to improve this, I would be lost without it!

**Comment by GracesGames** [comment]
Thank you very much for pointing this out to me. It is indeed necessary since the last update.
I have added the call to the [setup documentation](https://gracesgames.github.io/SimpleFileBrowser/setup/).

I hope that solves this issue. If so, feel free to close it. 
If you have any other request, please let me know :)
